// Code generated by protoc-gen-go.
// source: schema/common/options.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	schema/common/options.proto
	schema/common/fileref.proto
	go/common/testdata/testmsgs.proto

It has these top-level messages:
	Validation
	FileReference
	TestHasBadField
	TestHasGoodField
	TestHasBadSlice
	TestHasGoodSlice
	TestGoodOneOf
	TestBadOneOf
	TestBadValidateArgs
	TestBadReturnType
	TestBadProto
	TestGoodProto
	TestMessageWithOptions
	TestBadMessageWithOptions
	TestFileRefProto
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Validation_FieldType int32

const (
	// When applied to a 'string' field, implies that the field value cannot be
	// empty. This is the default for any field that has an external reference
	// restriction (i.e. one of 'host_env_ref', 'host_env', 'asset_ref',
	// 'asset').
	//
	// When applied to a 'repeated' field, implies that there must be at least
	// one instance of the field.
	//
	// When applied to 'oneof' implies that at least one of the alternatives must
	// be specified.
	//
	// Note that by default all fields with an annotation are required unless
	// they set the 'optional' property to true (see below). This FieldType
	// exists to make this clear when the only expected side-effect of adding
	// an annotation is to mark it as required.
	//
	// E.g.: Declare the 'h' field of Foo message to be required:
	//
	//     message Foo {
	//       string h = 1 [(v).type=REQUIRED]
	//     }
	Validation_REQUIRED Validation_FieldType = 0
	// This is an output field and is not expected to be populated in a asset
	// manifest literal. The field will be populated during the asset
	// resolution process and made available to downstream consumers of the
	// manifest.
	Validation_OUTPUT Validation_FieldType = 1
	// A ASSET field type indicates that the field refers to a resource defined
	// in the AssetManifest message. The value of the option should be an
	// exact match for the 'name' property of an object matching the 'key'
	// type.
	//
	// E.g.: Declare field 'h' of Foo message to be a reference to a Network
	// object.
	//
	//     message Foo {
	//       string h = 1 [(v)={type:ASSET, key:"network"}]
	//     }
	//
	// Alternatively, if the name of the field matches a field in
	// AssetManifest, then the key argument can be elided:
	//
	//     message Foo {
	//       string machine_type = 1 [(v).type:ASSET]
	//     }
	Validation_ASSET Validation_FieldType = 2
	// A HOST field type indicates that the field refers to a resource defined in
	// the HostEnvironment message. The value of the option should be an exact
	// match for the 'name' property of an object matching the 'key' type.
	//
	// E.g.: Declare field 'h' of Foo message to be a reference to a MachineType
	// object. The value of the 'h' field should match the 'name' property of a
	// MachineType object.
	//
	//     message Foo {
	//       string h = 1 [(v)={type:HOST, key:"machine_type"}]
	//     }
	//
	// Alternatively, if the name of the field matches a field in
	// HostEnvironment, then the key argument can be elided:
	//
	//     message Foo {
	//       string machine_type = 1 [(v).type:HOST]
	//     }
	Validation_HOST Validation_FieldType = 3
	// The field value cannot be empty and must match the <label> production in
	// RFC 1035. This is the default for any field named 'name'.
	Validation_LABEL Validation_FieldType = 4
	// The field value cannot be empty, and must match the <subdomains>
	// production in RFC 1035. Can only be applied to 'string' fields.
	Validation_FQDN Validation_FieldType = 5
)

var Validation_FieldType_name = map[int32]string{
	0: "REQUIRED",
	1: "OUTPUT",
	2: "ASSET",
	3: "HOST",
	4: "LABEL",
	5: "FQDN",
}
var Validation_FieldType_value = map[string]int32{
	"REQUIRED": 0,
	"OUTPUT":   1,
	"ASSET":    2,
	"HOST":     3,
	"LABEL":    4,
	"FQDN":     5,
}

func (x Validation_FieldType) String() string {
	return proto.EnumName(Validation_FieldType_name, int32(x))
}
func (Validation_FieldType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Validation struct {
	Type Validation_FieldType `protobuf:"varint,1,opt,name=type,enum=common.Validation_FieldType" json:"type,omitempty"`
	// The foreign key, if the key name is different from the field name. See the
	// FieldType documentation for examples of use.
	Key string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	// Indicates that the value is optional. By default adding an annotaiton to a
	// field marks it as a required field.
	Optional bool `protobuf:"varint,3,opt,name=optional" json:"optional,omitempty"`
}

func (m *Validation) Reset()                    { *m = Validation{} }
func (m *Validation) String() string            { return proto.CompactTextString(m) }
func (*Validation) ProtoMessage()               {}
func (*Validation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Validation) GetType() Validation_FieldType {
	if m != nil {
		return m.Type
	}
	return Validation_REQUIRED
}

func (m *Validation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Validation) GetOptional() bool {
	if m != nil {
		return m.Optional
	}
	return false
}

var E_V = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*Validation)(nil),
	Field:         50000,
	Name:          "common.v",
	Tag:           "bytes,50000,opt,name=v",
	Filename:      "schema/common/options.proto",
}

func init() {
	proto.RegisterType((*Validation)(nil), "common.Validation")
	proto.RegisterEnum("common.Validation_FieldType", Validation_FieldType_name, Validation_FieldType_value)
	proto.RegisterExtension(E_V)
}

func init() { proto.RegisterFile("schema/common/options.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4e, 0xc2, 0x40,
	0x18, 0xc4, 0x5d, 0xfe, 0xa5, 0x7c, 0x1a, 0xb3, 0xd9, 0x53, 0x83, 0x9a, 0x34, 0x9c, 0x38, 0x75,
	0x0d, 0x7a, 0xf2, 0x06, 0xa1, 0x44, 0x13, 0x62, 0xa5, 0x14, 0x0f, 0xde, 0x4a, 0xf9, 0x84, 0xc6,
	0x96, 0x6f, 0xb3, 0x2d, 0x24, 0xbc, 0x80, 0x6f, 0xe5, 0x3b, 0xf8, 0x48, 0x66, 0x59, 0xc4, 0x83,
	0xb7, 0xdd, 0xc9, 0x6f, 0x67, 0x67, 0x06, 0xae, 0xca, 0x74, 0x8d, 0x45, 0x22, 0x53, 0x2a, 0x0a,
	0xda, 0x48, 0x52, 0x55, 0x46, 0x9b, 0xd2, 0x57, 0x9a, 0x2a, 0x12, 0x2d, 0xab, 0x76, 0xbc, 0x15,
	0xd1, 0x2a, 0x47, 0x79, 0x50, 0x17, 0xdb, 0x77, 0xb9, 0xc4, 0x32, 0xd5, 0x99, 0xaa, 0x48, 0x5b,
	0xb2, 0xfb, 0xc5, 0x00, 0x5e, 0x93, 0x3c, 0x5b, 0x26, 0xe6, 0xbd, 0xb8, 0x85, 0x46, 0xb5, 0x57,
	0xe8, 0x32, 0x8f, 0xf5, 0x2e, 0xfb, 0xd7, 0xbe, 0xf5, 0xf1, 0xff, 0x08, 0x7f, 0x9c, 0x61, 0xbe,
	0x8c, 0xf7, 0x0a, 0xa3, 0x03, 0x29, 0x38, 0xd4, 0x3f, 0x70, 0xef, 0xd6, 0x3c, 0xd6, 0x6b, 0x47,
	0xe6, 0x28, 0x3a, 0xe0, 0xd8, 0x34, 0x49, 0xee, 0xd6, 0x3d, 0xd6, 0x73, 0xa2, 0xd3, 0xbd, 0x1b,
	0x42, 0xfb, 0x64, 0x20, 0x2e, 0xc0, 0x89, 0x82, 0xe9, 0xfc, 0x29, 0x0a, 0x46, 0xfc, 0x4c, 0x00,
	0xb4, 0xc2, 0x79, 0xfc, 0x32, 0x8f, 0x39, 0x13, 0x6d, 0x68, 0x0e, 0x66, 0xb3, 0x20, 0xe6, 0x35,
	0xe1, 0x40, 0xe3, 0x31, 0x9c, 0xc5, 0xbc, 0x6e, 0xc4, 0xc9, 0x60, 0x18, 0x4c, 0x78, 0xc3, 0x88,
	0xe3, 0xe9, 0xe8, 0x99, 0x37, 0x1f, 0x06, 0xc0, 0x76, 0xe2, 0xc6, 0xb7, 0x3d, 0xfd, 0xdf, 0x9e,
	0x36, 0x65, 0x68, 0x37, 0x71, 0xbf, 0x3f, 0x4d, 0x8c, 0xf3, 0xbe, 0xf8, 0x5f, 0x27, 0x62, 0xbb,
	0xe1, 0xfd, 0x5b, 0x3f, 0x5d, 0x6b, 0x2a, 0xb2, 0x6d, 0x71, 0xf4, 0x29, 0x69, 0xab, 0x53, 0x34,
	0xb4, 0xc4, 0x4d, 0x85, 0x5a, 0xe9, 0xac, 0x44, 0x99, 0x62, 0x2e, 0x57, 0x74, 0x1c, 0x7c, 0xd1,
	0x3a, 0xfc, 0x75, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xd1, 0x2b, 0x1b, 0x88, 0x01, 0x00,
	0x00,
}
