# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/asset/asset_manifest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema.asset import active_directory_pb2 as schema_dot_asset_dot_active__directory__pb2
from schema.asset import cert_pb2 as schema_dot_asset_dot_cert__pb2
from schema.asset import dns_pb2 as schema_dot_asset_dot_dns__pb2
from schema.asset import iis_pb2 as schema_dot_asset_dot_iis__pb2
from schema.asset import network_pb2 as schema_dot_asset_dot_network__pb2
from schema.asset import remote_desktop_pb2 as schema_dot_asset_dot_remote__desktop__pb2
from schema.common import validation_pb2 as schema_dot_common_dot_validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema/asset/asset_manifest.proto',
  package='asset',
  syntax='proto3',
  serialized_options=_b('Z1chromium.googlesource.com/enterprise/cel/go/asset'),
  serialized_pb=_b('\n!schema/asset/asset_manifest.proto\x12\x05\x61sset\x1a#schema/asset/active_directory.proto\x1a\x17schema/asset/cert.proto\x1a\x16schema/asset/dns.proto\x1a\x16schema/asset/iis.proto\x1a\x1aschema/asset/network.proto\x1a!schema/asset/remote_desktop.proto\x1a\x1eschema/common/validation.proto\"\xd4\x06\n\rAssetManifest\x12\'\n\x07network\x18\x01 \x03(\x0b\x32\x0e.asset.NetworkB\x06\x82\xb5\x18\x02\x08\x07\x12(\n\x08\x64ns_zone\x18\x02 \x03(\x0b\x32\x0e.asset.DNSZoneB\x06\x82\xb5\x18\x02\x08\x07\x12\x37\n\tad_domain\x18\x64 \x03(\x0b\x32\x1c.asset.ActiveDirectoryDomainB\x06\x82\xb5\x18\x02\x08\x07\x12P\n\x16\x61\x64_organizational_unit\x18\x65 \x03(\x0b\x32(.asset.ActiveDirectoryOrganizationalUnitB\x06\x82\xb5\x18\x02\x08\x07\x12\x42\n\x0f\x61\x64_group_policy\x18\x66 \x03(\x0b\x32!.asset.ActiveDirectoryGroupPolicyB\x06\x82\xb5\x18\x02\x08\x07\x12K\n\x14\x61\x64_group_policy_link\x18g \x03(\x0b\x32%.asset.ActiveDirectoryGroupPolicyLinkB\x06\x82\xb5\x18\x02\x08\x07\x12\x32\n\rwindows_group\x18h \x03(\x0b\x32\x13.asset.WindowsGroupB\x06\x82\xb5\x18\x02\x08\x07\x12\x36\n\x0fwindows_machine\x18i \x03(\x0b\x32\x15.asset.WindowsMachineB\x06\x82\xb5\x18\x02\x08\x07\x12\x30\n\x0cwindows_user\x18j \x03(\x0b\x32\x12.asset.WindowsUserB\x06\x82\xb5\x18\x02\x08\x07\x12\x30\n\x0b\x63\x65rtificate\x18\xc8\x01 \x03(\x0b\x32\x12.asset.CertificateB\x06\x82\xb5\x18\x02\x08\x07\x12\x39\n\x10\x63\x65rtificate_pool\x18\xc9\x01 \x03(\x0b\x32\x16.asset.CertificatePoolB\x06\x82\xb5\x18\x02\x08\x07\x12\x37\n\x0fiis_application\x18\xac\x02 \x03(\x0b\x32\x15.asset.IISApplicationB\x06\x82\xb5\x18\x02\x08\x07\x12-\n\niis_server\x18\xad\x02 \x03(\x0b\x32\x10.asset.IISServerB\x06\x82\xb5\x18\x02\x08\x07\x12)\n\x08iis_site\x18\xae\x02 \x03(\x0b\x32\x0e.asset.IISSiteB\x06\x82\xb5\x18\x02\x08\x07\x12\x36\n\x13remote_desktop_host\x18\x90\x03 \x03(\x0b\x32\x18.asset.RemoteDesktopHostB3Z1chromium.googlesource.com/enterprise/cel/go/assetb\x06proto3')
  ,
  dependencies=[schema_dot_asset_dot_active__directory__pb2.DESCRIPTOR,schema_dot_asset_dot_cert__pb2.DESCRIPTOR,schema_dot_asset_dot_dns__pb2.DESCRIPTOR,schema_dot_asset_dot_iis__pb2.DESCRIPTOR,schema_dot_asset_dot_network__pb2.DESCRIPTOR,schema_dot_asset_dot_remote__desktop__pb2.DESCRIPTOR,schema_dot_common_dot_validation__pb2.DESCRIPTOR,])




_ASSETMANIFEST = _descriptor.Descriptor(
  name='AssetManifest',
  full_name='asset.AssetManifest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='asset.AssetManifest.network', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dns_zone', full_name='asset.AssetManifest.dns_zone', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_domain', full_name='asset.AssetManifest.ad_domain', index=2,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_organizational_unit', full_name='asset.AssetManifest.ad_organizational_unit', index=3,
      number=101, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_group_policy', full_name='asset.AssetManifest.ad_group_policy', index=4,
      number=102, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ad_group_policy_link', full_name='asset.AssetManifest.ad_group_policy_link', index=5,
      number=103, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='windows_group', full_name='asset.AssetManifest.windows_group', index=6,
      number=104, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='windows_machine', full_name='asset.AssetManifest.windows_machine', index=7,
      number=105, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='windows_user', full_name='asset.AssetManifest.windows_user', index=8,
      number=106, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='certificate', full_name='asset.AssetManifest.certificate', index=9,
      number=200, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='certificate_pool', full_name='asset.AssetManifest.certificate_pool', index=10,
      number=201, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iis_application', full_name='asset.AssetManifest.iis_application', index=11,
      number=300, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iis_server', full_name='asset.AssetManifest.iis_server', index=12,
      number=301, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='iis_site', full_name='asset.AssetManifest.iis_site', index=13,
      number=302, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\007'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remote_desktop_host', full_name='asset.AssetManifest.remote_desktop_host', index=14,
      number=400, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=1102,
)

_ASSETMANIFEST.fields_by_name['network'].message_type = schema_dot_asset_dot_network__pb2._NETWORK
_ASSETMANIFEST.fields_by_name['dns_zone'].message_type = schema_dot_asset_dot_dns__pb2._DNSZONE
_ASSETMANIFEST.fields_by_name['ad_domain'].message_type = schema_dot_asset_dot_active__directory__pb2._ACTIVEDIRECTORYDOMAIN
_ASSETMANIFEST.fields_by_name['ad_organizational_unit'].message_type = schema_dot_asset_dot_active__directory__pb2._ACTIVEDIRECTORYORGANIZATIONALUNIT
_ASSETMANIFEST.fields_by_name['ad_group_policy'].message_type = schema_dot_asset_dot_active__directory__pb2._ACTIVEDIRECTORYGROUPPOLICY
_ASSETMANIFEST.fields_by_name['ad_group_policy_link'].message_type = schema_dot_asset_dot_active__directory__pb2._ACTIVEDIRECTORYGROUPPOLICYLINK
_ASSETMANIFEST.fields_by_name['windows_group'].message_type = schema_dot_asset_dot_active__directory__pb2._WINDOWSGROUP
_ASSETMANIFEST.fields_by_name['windows_machine'].message_type = schema_dot_asset_dot_active__directory__pb2._WINDOWSMACHINE
_ASSETMANIFEST.fields_by_name['windows_user'].message_type = schema_dot_asset_dot_active__directory__pb2._WINDOWSUSER
_ASSETMANIFEST.fields_by_name['certificate'].message_type = schema_dot_asset_dot_cert__pb2._CERTIFICATE
_ASSETMANIFEST.fields_by_name['certificate_pool'].message_type = schema_dot_asset_dot_cert__pb2._CERTIFICATEPOOL
_ASSETMANIFEST.fields_by_name['iis_application'].message_type = schema_dot_asset_dot_iis__pb2._IISAPPLICATION
_ASSETMANIFEST.fields_by_name['iis_server'].message_type = schema_dot_asset_dot_iis__pb2._IISSERVER
_ASSETMANIFEST.fields_by_name['iis_site'].message_type = schema_dot_asset_dot_iis__pb2._IISSITE
_ASSETMANIFEST.fields_by_name['remote_desktop_host'].message_type = schema_dot_asset_dot_remote__desktop__pb2._REMOTEDESKTOPHOST
DESCRIPTOR.message_types_by_name['AssetManifest'] = _ASSETMANIFEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssetManifest = _reflection.GeneratedProtocolMessageType('AssetManifest', (_message.Message,), dict(
  DESCRIPTOR = _ASSETMANIFEST,
  __module__ = 'schema.asset.asset_manifest_pb2'
  # @@protoc_insertion_point(class_scope:asset.AssetManifest)
  ))
_sym_db.RegisterMessage(AssetManifest)


DESCRIPTOR._options = None
_ASSETMANIFEST.fields_by_name['network']._options = None
_ASSETMANIFEST.fields_by_name['dns_zone']._options = None
_ASSETMANIFEST.fields_by_name['ad_domain']._options = None
_ASSETMANIFEST.fields_by_name['ad_organizational_unit']._options = None
_ASSETMANIFEST.fields_by_name['ad_group_policy']._options = None
_ASSETMANIFEST.fields_by_name['ad_group_policy_link']._options = None
_ASSETMANIFEST.fields_by_name['windows_group']._options = None
_ASSETMANIFEST.fields_by_name['windows_machine']._options = None
_ASSETMANIFEST.fields_by_name['windows_user']._options = None
_ASSETMANIFEST.fields_by_name['certificate']._options = None
_ASSETMANIFEST.fields_by_name['certificate_pool']._options = None
_ASSETMANIFEST.fields_by_name['iis_application']._options = None
_ASSETMANIFEST.fields_by_name['iis_server']._options = None
_ASSETMANIFEST.fields_by_name['iis_site']._options = None
# @@protoc_insertion_point(module_scope)
