# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/asset/dns.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema.common import validation_pb2 as schema_dot_common_dot_validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema/asset/dns.proto',
  package='asset',
  syntax='proto3',
  serialized_options=_b('Z1chromium.googlesource.com/enterprise/cel/go/asset'),
  serialized_pb=_b('\n\x16schema/asset/dns.proto\x12\x05\x61sset\x1a\x1eschema/common/validation.proto\"A\n\x07\x44NSZone\x12\x14\n\x04name\x18\x01 \x01(\tB\x06\x82\xb5\x18\x02\x08\x03\x12 \n\x06record\x18\x02 \x03(\x0b\x32\x10.asset.DNSRecord\"\x93\x01\n\tDNSRecord\x12\x14\n\x04name\x18\x01 \x01(\tB\x06\x82\xb5\x18\x02\x08\x02\x12\x13\n\x03ttl\x18\x02 \x01(\x05\x42\x06\x82\xb5\x18\x02\x08\x01\x12\x14\n\x0crecord_class\x18\x03 \x01(\t\x12\x1b\n\x0brecord_type\x18\x04 \x01(\tB\x06\x82\xb5\x18\x02\x08\x01\x12\x10\n\x08priority\x18\x05 \x01(\x05\x12\x16\n\x06\x61nswer\x18\x06 \x01(\tB\x06\x82\xb5\x18\x02\x08\x01\x42\x33Z1chromium.googlesource.com/enterprise/cel/go/assetb\x06proto3')
  ,
  dependencies=[schema_dot_common_dot_validation__pb2.DESCRIPTOR,])




_DNSZONE = _descriptor.Descriptor(
  name='DNSZone',
  full_name='asset.DNSZone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='asset.DNSZone.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\003'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record', full_name='asset.DNSZone.record', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=130,
)


_DNSRECORD = _descriptor.Descriptor(
  name='DNSRecord',
  full_name='asset.DNSRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='asset.DNSRecord.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\002'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ttl', full_name='asset.DNSRecord.ttl', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_class', full_name='asset.DNSRecord.record_class', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='record_type', full_name='asset.DNSRecord.record_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='priority', full_name='asset.DNSRecord.priority', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='answer', full_name='asset.DNSRecord.answer', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=280,
)

_DNSZONE.fields_by_name['record'].message_type = _DNSRECORD
DESCRIPTOR.message_types_by_name['DNSZone'] = _DNSZONE
DESCRIPTOR.message_types_by_name['DNSRecord'] = _DNSRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DNSZone = _reflection.GeneratedProtocolMessageType('DNSZone', (_message.Message,), dict(
  DESCRIPTOR = _DNSZONE,
  __module__ = 'schema.asset.dns_pb2'
  # @@protoc_insertion_point(class_scope:asset.DNSZone)
  ))
_sym_db.RegisterMessage(DNSZone)

DNSRecord = _reflection.GeneratedProtocolMessageType('DNSRecord', (_message.Message,), dict(
  DESCRIPTOR = _DNSRECORD,
  __module__ = 'schema.asset.dns_pb2'
  # @@protoc_insertion_point(class_scope:asset.DNSRecord)
  ))
_sym_db.RegisterMessage(DNSRecord)


DESCRIPTOR._options = None
_DNSZONE.fields_by_name['name']._options = None
_DNSRECORD.fields_by_name['name']._options = None
_DNSRECORD.fields_by_name['ttl']._options = None
_DNSRECORD.fields_by_name['record_type']._options = None
_DNSRECORD.fields_by_name['answer']._options = None
# @@protoc_insertion_point(module_scope)
