# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/asset/machine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from schema.asset import network_pb2 as schema_dot_asset_dot_network__pb2
from schema.common import validation_pb2 as schema_dot_common_dot_validation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema/asset/machine.proto',
  package='asset',
  syntax='proto3',
  serialized_options=_b('Z1chromium.googlesource.com/enterprise/cel/go/asset'),
  serialized_pb=_b('\n\x1aschema/asset/machine.proto\x12\x05\x61sset\x1a\x1aschema/asset/network.proto\x1a\x1eschema/common/validation.proto\"f\n\x10NetworkInterface\x12&\n\x07network\x18\x01 \x01(\tB\x15\x82\xb5\x18\x11\x08\x01\x12\rasset.network\x12*\n\rfixed_address\x18\x02 \x01(\x0b\x32\x13.asset.FixedAddress\"\x82\x01\n\x07Machine\x12\x0c\n\x04name\x18\x01 \x01(\t\x12-\n\x0cmachine_type\x18\x02 \x01(\tB\x17\x82\xb5\x18\x13\x12\x11host.machine_type\x12:\n\x11network_interface\x18\x03 \x03(\x0b\x32\x17.asset.NetworkInterfaceB\x06\x82\xb5\x18\x02\x08\x01\x42\x33Z1chromium.googlesource.com/enterprise/cel/go/assetb\x06proto3')
  ,
  dependencies=[schema_dot_asset_dot_network__pb2.DESCRIPTOR,schema_dot_common_dot_validation__pb2.DESCRIPTOR,])




_NETWORKINTERFACE = _descriptor.Descriptor(
  name='NetworkInterface',
  full_name='asset.NetworkInterface',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='network', full_name='asset.NetworkInterface.network', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\021\010\001\022\rasset.network'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fixed_address', full_name='asset.NetworkInterface.fixed_address', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=199,
)


_MACHINE = _descriptor.Descriptor(
  name='Machine',
  full_name='asset.Machine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='asset.Machine.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_type', full_name='asset.Machine.machine_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\023\022\021host.machine_type'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='network_interface', full_name='asset.Machine.network_interface', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202\265\030\002\010\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=332,
)

_NETWORKINTERFACE.fields_by_name['fixed_address'].message_type = schema_dot_asset_dot_network__pb2._FIXEDADDRESS
_MACHINE.fields_by_name['network_interface'].message_type = _NETWORKINTERFACE
DESCRIPTOR.message_types_by_name['NetworkInterface'] = _NETWORKINTERFACE
DESCRIPTOR.message_types_by_name['Machine'] = _MACHINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkInterface = _reflection.GeneratedProtocolMessageType('NetworkInterface', (_message.Message,), dict(
  DESCRIPTOR = _NETWORKINTERFACE,
  __module__ = 'schema.asset.machine_pb2'
  # @@protoc_insertion_point(class_scope:asset.NetworkInterface)
  ))
_sym_db.RegisterMessage(NetworkInterface)

Machine = _reflection.GeneratedProtocolMessageType('Machine', (_message.Message,), dict(
  DESCRIPTOR = _MACHINE,
  __module__ = 'schema.asset.machine_pb2'
  # @@protoc_insertion_point(class_scope:asset.Machine)
  ))
_sym_db.RegisterMessage(Machine)


DESCRIPTOR._options = None
_NETWORKINTERFACE.fields_by_name['network']._options = None
_MACHINE.fields_by_name['machine_type']._options = None
_MACHINE.fields_by_name['network_interface']._options = None
# @@protoc_insertion_point(module_scope)
