# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema/common/validation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='schema/common/validation.proto',
  package='common',
  syntax='proto3',
  serialized_options=_b('Z2chromium.googlesource.com/enterprise/cel/go/common'),
  serialized_pb=_b('\n\x1eschema/common/validation.proto\x12\x06\x63ommon\x1a google/protobuf/descriptor.proto\"\xdc\x01\n\nValidation\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.common.Validation.FieldType\x12\x0b\n\x03ref\x18\x02 \x01(\t\x12\x12\n\x08optional\x18\x03 \x01(\x08H\x00\"p\n\tFieldType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08REQUIRED\x10\x01\x12\t\n\x05LABEL\x10\x02\x12\x08\n\x04\x46QDN\x10\x03\x12\x0c\n\x08ORGLABEL\x10\x04\x12\n\n\x06OUTPUT\x10\x05\x12\x0b\n\x07RUNTIME\x10\x06\x12\x0c\n\x08TOPLEVEL\x10\x07\x42\x0f\n\roptional_flag:>\n\x01v\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x12.common.ValidationB4Z2chromium.googlesource.com/enterprise/cel/go/commonb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])


V_FIELD_NUMBER = 50000
v = _descriptor.FieldDescriptor(
  name='v', full_name='common.v', index=0,
  number=50000, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)

_VALIDATION_FIELDTYPE = _descriptor.EnumDescriptor(
  name='FieldType',
  full_name='common.Validation.FieldType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUIRED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LABEL', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FQDN', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ORGLABEL', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OUTPUT', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNTIME', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOPLEVEL', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=168,
  serialized_end=280,
)
_sym_db.RegisterEnumDescriptor(_VALIDATION_FIELDTYPE)


_VALIDATION = _descriptor.Descriptor(
  name='Validation',
  full_name='common.Validation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='common.Validation.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ref', full_name='common.Validation.ref', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='optional', full_name='common.Validation.optional', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VALIDATION_FIELDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='optional_flag', full_name='common.Validation.optional_flag',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=77,
  serialized_end=297,
)

_VALIDATION.fields_by_name['type'].enum_type = _VALIDATION_FIELDTYPE
_VALIDATION_FIELDTYPE.containing_type = _VALIDATION
_VALIDATION.oneofs_by_name['optional_flag'].fields.append(
  _VALIDATION.fields_by_name['optional'])
_VALIDATION.fields_by_name['optional'].containing_oneof = _VALIDATION.oneofs_by_name['optional_flag']
DESCRIPTOR.message_types_by_name['Validation'] = _VALIDATION
DESCRIPTOR.extensions_by_name['v'] = v
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Validation = _reflection.GeneratedProtocolMessageType('Validation', (_message.Message,), dict(
  DESCRIPTOR = _VALIDATION,
  __module__ = 'schema.common.validation_pb2'
  # @@protoc_insertion_point(class_scope:common.Validation)
  ))
_sym_db.RegisterMessage(Validation)

v.message_type = _VALIDATION
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(v)

DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
