// This is a generated file. Do not modify directly.

// This ProtoBuf source file is based on the REST protocol defintion for the
// service at https://www.googleapis.com/compute/beta/projects/.
//
// Compute Engine API:Creates and runs virtual machines on Google Cloud Platform.
// 
// API Name      : compute (compute:beta)
// Version       : beta
// Revision      : 20170908
// Documentation : https://developers.google.com/compute/docs/reference/latest/

package compute

// All trivial validators.

func (*AcceleratorConfig) Validate() error { return nil }
func (*AcceleratorType) Validate() error { return nil }
func (*AcceleratorTypeAggregatedList) Validate() error { return nil }
func (*AcceleratorTypeAggregatedList_Warning) Validate() error { return nil }
func (*AcceleratorTypeList) Validate() error { return nil }
func (*AcceleratorTypeList_Warning) Validate() error { return nil }
func (*AcceleratorTypesScopedList) Validate() error { return nil }
func (*AcceleratorTypesScopedList_Warning) Validate() error { return nil }
func (*AccessConfig) Validate() error { return nil }
func (*Address) Validate() error { return nil }
func (*AddressAggregatedList) Validate() error { return nil }
func (*AddressAggregatedList_Warning) Validate() error { return nil }
func (*AddressList) Validate() error { return nil }
func (*AddressList_Warning) Validate() error { return nil }
func (*AddressesScopedList) Validate() error { return nil }
func (*AddressesScopedList_Warning) Validate() error { return nil }
func (*AliasIpRange) Validate() error { return nil }
func (*AttachedDisk) Validate() error { return nil }
func (*AttachedDiskInitializeParams) Validate() error { return nil }
func (*AuditConfig) Validate() error { return nil }
func (*AuditLogConfig) Validate() error { return nil }
func (*AuthorizationLoggingOptions) Validate() error { return nil }
func (*Autoscaler) Validate() error { return nil }
func (*AutoscalerAggregatedList) Validate() error { return nil }
func (*AutoscalerAggregatedList_Warning) Validate() error { return nil }
func (*AutoscalerList) Validate() error { return nil }
func (*AutoscalerList_Warning) Validate() error { return nil }
func (*AutoscalerStatusDetails) Validate() error { return nil }
func (*AutoscalersScopedList) Validate() error { return nil }
func (*AutoscalersScopedList_Warning) Validate() error { return nil }
func (*AutoscalingPolicy) Validate() error { return nil }
func (*AutoscalingPolicyCpuUtilization) Validate() error { return nil }
func (*AutoscalingPolicyCustomMetricUtilization) Validate() error { return nil }
func (*AutoscalingPolicyLoadBalancingUtilization) Validate() error { return nil }
func (*Backend) Validate() error { return nil }
func (*BackendBucket) Validate() error { return nil }
func (*BackendBucketList) Validate() error { return nil }
func (*BackendBucketList_Warning) Validate() error { return nil }
func (*BackendService) Validate() error { return nil }
func (*BackendServiceAggregatedList) Validate() error { return nil }
func (*BackendServiceAggregatedList_Warning) Validate() error { return nil }
func (*BackendServiceCdnPolicy) Validate() error { return nil }
func (*BackendServiceGroupHealth) Validate() error { return nil }
func (*BackendServiceIAP) Validate() error { return nil }
func (*BackendServiceList) Validate() error { return nil }
func (*BackendServiceList_Warning) Validate() error { return nil }
func (*BackendServicesScopedList) Validate() error { return nil }
func (*BackendServicesScopedList_Warning) Validate() error { return nil }
func (*Binding) Validate() error { return nil }
func (*CacheInvalidationRule) Validate() error { return nil }
func (*CacheKeyPolicy) Validate() error { return nil }
func (*Commitment) Validate() error { return nil }
func (*CommitmentAggregatedList) Validate() error { return nil }
func (*CommitmentAggregatedList_Warning) Validate() error { return nil }
func (*CommitmentList) Validate() error { return nil }
func (*CommitmentList_Warning) Validate() error { return nil }
func (*CommitmentsScopedList) Validate() error { return nil }
func (*CommitmentsScopedList_Warning) Validate() error { return nil }
func (*Condition) Validate() error { return nil }
func (*ConnectionDraining) Validate() error { return nil }
func (*CustomerEncryptionKey) Validate() error { return nil }
func (*CustomerEncryptionKeyProtectedDisk) Validate() error { return nil }
func (*DeprecationStatus) Validate() error { return nil }
func (*Disk) Validate() error { return nil }
func (*DiskAggregatedList) Validate() error { return nil }
func (*DiskAggregatedList_Warning) Validate() error { return nil }
func (*DiskList) Validate() error { return nil }
func (*DiskList_Warning) Validate() error { return nil }
func (*DiskMoveRequest) Validate() error { return nil }
func (*DiskType) Validate() error { return nil }
func (*DiskTypeAggregatedList) Validate() error { return nil }
func (*DiskTypeAggregatedList_Warning) Validate() error { return nil }
func (*DiskTypeList) Validate() error { return nil }
func (*DiskTypeList_Warning) Validate() error { return nil }
func (*DiskTypesScopedList) Validate() error { return nil }
func (*DiskTypesScopedList_Warning) Validate() error { return nil }
func (*DisksResizeRequest) Validate() error { return nil }
func (*DisksScopedList) Validate() error { return nil }
func (*DisksScopedList_Warning) Validate() error { return nil }
func (*DistributionPolicy) Validate() error { return nil }
func (*DistributionPolicyZoneConfiguration) Validate() error { return nil }
func (*Expr) Validate() error { return nil }
func (*Firewall) Validate() error { return nil }
func (*FirewallList) Validate() error { return nil }
func (*FirewallList_Warning) Validate() error { return nil }
func (*Firewall_Allowed) Validate() error { return nil }
func (*Firewall_Denied) Validate() error { return nil }
func (*FixedOrPercent) Validate() error { return nil }
func (*ForwardingRule) Validate() error { return nil }
func (*ForwardingRuleAggregatedList) Validate() error { return nil }
func (*ForwardingRuleAggregatedList_Warning) Validate() error { return nil }
func (*ForwardingRuleList) Validate() error { return nil }
func (*ForwardingRuleList_Warning) Validate() error { return nil }
func (*ForwardingRulesScopedList) Validate() error { return nil }
func (*ForwardingRulesScopedList_Warning) Validate() error { return nil }
func (*GlobalSetLabelsRequest) Validate() error { return nil }
func (*GuestOsFeature) Validate() error { return nil }
func (*HTTPHealthCheck) Validate() error { return nil }
func (*HTTPSHealthCheck) Validate() error { return nil }
func (*HealthCheck) Validate() error { return nil }
func (*HealthCheckList) Validate() error { return nil }
func (*HealthCheckList_Warning) Validate() error { return nil }
func (*HealthCheckReference) Validate() error { return nil }
func (*HealthStatus) Validate() error { return nil }
func (*HostRule) Validate() error { return nil }
func (*HttpHealthCheck) Validate() error { return nil }
func (*HttpHealthCheckList) Validate() error { return nil }
func (*HttpHealthCheckList_Warning) Validate() error { return nil }
func (*HttpsHealthCheck) Validate() error { return nil }
func (*HttpsHealthCheckList) Validate() error { return nil }
func (*HttpsHealthCheckList_Warning) Validate() error { return nil }
func (*Image) Validate() error { return nil }
func (*ImageList) Validate() error { return nil }
func (*ImageList_Warning) Validate() error { return nil }
func (*Image_RawDisk) Validate() error { return nil }
func (*Instance) Validate() error { return nil }
func (*InstanceAggregatedList) Validate() error { return nil }
func (*InstanceAggregatedList_Warning) Validate() error { return nil }
func (*InstanceGroup) Validate() error { return nil }
func (*InstanceGroupAggregatedList) Validate() error { return nil }
func (*InstanceGroupAggregatedList_Warning) Validate() error { return nil }
func (*InstanceGroupList) Validate() error { return nil }
func (*InstanceGroupList_Warning) Validate() error { return nil }
func (*InstanceGroupManager) Validate() error { return nil }
func (*InstanceGroupManagerActionsSummary) Validate() error { return nil }
func (*InstanceGroupManagerAggregatedList) Validate() error { return nil }
func (*InstanceGroupManagerAggregatedList_Warning) Validate() error { return nil }
func (*InstanceGroupManagerAutoHealingPolicy) Validate() error { return nil }
func (*InstanceGroupManagerList) Validate() error { return nil }
func (*InstanceGroupManagerList_Warning) Validate() error { return nil }
func (*InstanceGroupManagerPendingActionsSummary) Validate() error { return nil }
func (*InstanceGroupManagerUpdatePolicy) Validate() error { return nil }
func (*InstanceGroupManagerVersion) Validate() error { return nil }
func (*InstanceGroupManagersAbandonInstancesRequest) Validate() error { return nil }
func (*InstanceGroupManagersDeleteInstancesRequest) Validate() error { return nil }
func (*InstanceGroupManagersListManagedInstancesResponse) Validate() error { return nil }
func (*InstanceGroupManagersRecreateInstancesRequest) Validate() error { return nil }
func (*InstanceGroupManagersResizeAdvancedRequest) Validate() error { return nil }
func (*InstanceGroupManagersScopedList) Validate() error { return nil }
func (*InstanceGroupManagersScopedList_Warning) Validate() error { return nil }
func (*InstanceGroupManagersSetAutoHealingRequest) Validate() error { return nil }
func (*InstanceGroupManagersSetInstanceTemplateRequest) Validate() error { return nil }
func (*InstanceGroupManagersSetTargetPoolsRequest) Validate() error { return nil }
func (*InstanceGroupsAddInstancesRequest) Validate() error { return nil }
func (*InstanceGroupsListInstances) Validate() error { return nil }
func (*InstanceGroupsListInstancesRequest) Validate() error { return nil }
func (*InstanceGroupsListInstances_Warning) Validate() error { return nil }
func (*InstanceGroupsRemoveInstancesRequest) Validate() error { return nil }
func (*InstanceGroupsScopedList) Validate() error { return nil }
func (*InstanceGroupsScopedList_Warning) Validate() error { return nil }
func (*InstanceGroupsSetNamedPortsRequest) Validate() error { return nil }
func (*InstanceList) Validate() error { return nil }
func (*InstanceListReferrers) Validate() error { return nil }
func (*InstanceListReferrers_Warning) Validate() error { return nil }
func (*InstanceList_Warning) Validate() error { return nil }
func (*InstanceMoveRequest) Validate() error { return nil }
func (*InstanceProperties) Validate() error { return nil }
func (*InstanceReference) Validate() error { return nil }
func (*InstanceTemplate) Validate() error { return nil }
func (*InstanceTemplateList) Validate() error { return nil }
func (*InstanceTemplateList_Warning) Validate() error { return nil }
func (*InstanceWithNamedPorts) Validate() error { return nil }
func (*InstancesScopedList) Validate() error { return nil }
func (*InstancesScopedList_Warning) Validate() error { return nil }
func (*InstancesSetLabelsRequest) Validate() error { return nil }
func (*InstancesSetMachineResourcesRequest) Validate() error { return nil }
func (*InstancesSetMachineTypeRequest) Validate() error { return nil }
func (*InstancesSetMinCpuPlatformRequest) Validate() error { return nil }
func (*InstancesSetServiceAccountRequest) Validate() error { return nil }
func (*InstancesStartWithEncryptionKeyRequest) Validate() error { return nil }
func (*Interconnect) Validate() error { return nil }
func (*InterconnectAttachment) Validate() error { return nil }
func (*InterconnectAttachmentAggregatedList) Validate() error { return nil }
func (*InterconnectAttachmentAggregatedList_Warning) Validate() error { return nil }
func (*InterconnectAttachmentList) Validate() error { return nil }
func (*InterconnectAttachmentList_Warning) Validate() error { return nil }
func (*InterconnectAttachmentPrivateInfo) Validate() error { return nil }
func (*InterconnectAttachmentsScopedList) Validate() error { return nil }
func (*InterconnectAttachmentsScopedList_Warning) Validate() error { return nil }
func (*InterconnectCircuitInfo) Validate() error { return nil }
func (*InterconnectList) Validate() error { return nil }
func (*InterconnectList_Warning) Validate() error { return nil }
func (*InterconnectLocation) Validate() error { return nil }
func (*InterconnectLocationList) Validate() error { return nil }
func (*InterconnectLocationList_Warning) Validate() error { return nil }
func (*InterconnectLocationRegionInfo) Validate() error { return nil }
func (*InterconnectOutageNotification) Validate() error { return nil }
func (*License) Validate() error { return nil }
func (*LogConfig) Validate() error { return nil }
func (*LogConfigCloudAuditOptions) Validate() error { return nil }
func (*LogConfigCounterOptions) Validate() error { return nil }
func (*LogConfigDataAccessOptions) Validate() error { return nil }
func (*MachineType) Validate() error { return nil }
func (*MachineTypeAggregatedList) Validate() error { return nil }
func (*MachineTypeAggregatedList_Warning) Validate() error { return nil }
func (*MachineTypeList) Validate() error { return nil }
func (*MachineTypeList_Warning) Validate() error { return nil }
func (*MachineTypesScopedList) Validate() error { return nil }
func (*MachineTypesScopedList_Warning) Validate() error { return nil }
func (*ManagedInstance) Validate() error { return nil }
func (*ManagedInstanceLastAttempt) Validate() error { return nil }
func (*ManagedInstanceLastAttempt_Errors) Validate() error { return nil }
func (*ManagedInstanceVersion) Validate() error { return nil }
func (*Metadata) Validate() error { return nil }
func (*Metadata_Items) Validate() error { return nil }
func (*NamedPort) Validate() error { return nil }
func (*Network) Validate() error { return nil }
func (*NetworkInterface) Validate() error { return nil }
func (*NetworkList) Validate() error { return nil }
func (*NetworkList_Warning) Validate() error { return nil }
func (*NetworkPeering) Validate() error { return nil }
func (*NetworkRoutingConfig) Validate() error { return nil }
func (*NetworksAddPeeringRequest) Validate() error { return nil }
func (*NetworksRemovePeeringRequest) Validate() error { return nil }
func (*Operation) Validate() error { return nil }
func (*OperationAggregatedList) Validate() error { return nil }
func (*OperationAggregatedList_Warning) Validate() error { return nil }
func (*OperationList) Validate() error { return nil }
func (*OperationList_Warning) Validate() error { return nil }
func (*Operation_Error) Validate() error { return nil }
func (*Operation_Warnings) Validate() error { return nil }
func (*OperationsScopedList) Validate() error { return nil }
func (*OperationsScopedList_Warning) Validate() error { return nil }
func (*PathMatcher) Validate() error { return nil }
func (*PathRule) Validate() error { return nil }
func (*Policy) Validate() error { return nil }
func (*Project) Validate() error { return nil }
func (*ProjectsDisableXpnResourceRequest) Validate() error { return nil }
func (*ProjectsEnableXpnResourceRequest) Validate() error { return nil }
func (*ProjectsGetXpnResources) Validate() error { return nil }
func (*ProjectsListXpnHostsRequest) Validate() error { return nil }
func (*Quota) Validate() error { return nil }
func (*Reference) Validate() error { return nil }
func (*Region) Validate() error { return nil }
func (*RegionAutoscalerList) Validate() error { return nil }
func (*RegionAutoscalerList_Warning) Validate() error { return nil }
func (*RegionInstanceGroupList) Validate() error { return nil }
func (*RegionInstanceGroupList_Warning) Validate() error { return nil }
func (*RegionInstanceGroupManagerList) Validate() error { return nil }
func (*RegionInstanceGroupManagerList_Warning) Validate() error { return nil }
func (*RegionInstanceGroupManagersAbandonInstancesRequest) Validate() error { return nil }
func (*RegionInstanceGroupManagersDeleteInstancesRequest) Validate() error { return nil }
func (*RegionInstanceGroupManagersListInstancesResponse) Validate() error { return nil }
func (*RegionInstanceGroupManagersRecreateRequest) Validate() error { return nil }
func (*RegionInstanceGroupManagersSetAutoHealingRequest) Validate() error { return nil }
func (*RegionInstanceGroupManagersSetTargetPoolsRequest) Validate() error { return nil }
func (*RegionInstanceGroupManagersSetTemplateRequest) Validate() error { return nil }
func (*RegionInstanceGroupsListInstances) Validate() error { return nil }
func (*RegionInstanceGroupsListInstancesRequest) Validate() error { return nil }
func (*RegionInstanceGroupsListInstances_Warning) Validate() error { return nil }
func (*RegionInstanceGroupsSetNamedPortsRequest) Validate() error { return nil }
func (*RegionList) Validate() error { return nil }
func (*RegionList_Warning) Validate() error { return nil }
func (*RegionSetLabelsRequest) Validate() error { return nil }
func (*ResourceCommitment) Validate() error { return nil }
func (*ResourceGroupReference) Validate() error { return nil }
func (*Route) Validate() error { return nil }
func (*RouteList) Validate() error { return nil }
func (*RouteList_Warning) Validate() error { return nil }
func (*Route_Warnings) Validate() error { return nil }
func (*Router) Validate() error { return nil }
func (*RouterAggregatedList) Validate() error { return nil }
func (*RouterAggregatedList_Warning) Validate() error { return nil }
func (*RouterBgp) Validate() error { return nil }
func (*RouterBgpPeer) Validate() error { return nil }
func (*RouterInterface) Validate() error { return nil }
func (*RouterList) Validate() error { return nil }
func (*RouterList_Warning) Validate() error { return nil }
func (*RouterStatus) Validate() error { return nil }
func (*RouterStatusBgpPeerStatus) Validate() error { return nil }
func (*RouterStatusResponse) Validate() error { return nil }
func (*RoutersPreviewResponse) Validate() error { return nil }
func (*RoutersScopedList) Validate() error { return nil }
func (*RoutersScopedList_Warning) Validate() error { return nil }
func (*Rule) Validate() error { return nil }
func (*SSLHealthCheck) Validate() error { return nil }
func (*Scheduling) Validate() error { return nil }
func (*SecurityPolicy) Validate() error { return nil }
func (*SecurityPolicyList) Validate() error { return nil }
func (*SecurityPolicyList_Warning) Validate() error { return nil }
func (*SecurityPolicyReference) Validate() error { return nil }
func (*SecurityPolicyRule) Validate() error { return nil }
func (*SecurityPolicyRuleMatcher) Validate() error { return nil }
func (*SerialPortOutput) Validate() error { return nil }
func (*ServiceAccount) Validate() error { return nil }
func (*Snapshot) Validate() error { return nil }
func (*SnapshotList) Validate() error { return nil }
func (*SnapshotList_Warning) Validate() error { return nil }
func (*SslCertificate) Validate() error { return nil }
func (*SslCertificateList) Validate() error { return nil }
func (*SslCertificateList_Warning) Validate() error { return nil }
func (*Subnetwork) Validate() error { return nil }
func (*SubnetworkAggregatedList) Validate() error { return nil }
func (*SubnetworkAggregatedList_Warning) Validate() error { return nil }
func (*SubnetworkList) Validate() error { return nil }
func (*SubnetworkList_Warning) Validate() error { return nil }
func (*SubnetworkSecondaryRange) Validate() error { return nil }
func (*SubnetworksExpandIpCidrRangeRequest) Validate() error { return nil }
func (*SubnetworksScopedList) Validate() error { return nil }
func (*SubnetworksScopedList_Warning) Validate() error { return nil }
func (*SubnetworksSetPrivateIpGoogleAccessRequest) Validate() error { return nil }
func (*TCPHealthCheck) Validate() error { return nil }
func (*Tags) Validate() error { return nil }
func (*TargetHttpProxy) Validate() error { return nil }
func (*TargetHttpProxyList) Validate() error { return nil }
func (*TargetHttpProxyList_Warning) Validate() error { return nil }
func (*TargetHttpsProxiesSetSslCertificatesRequest) Validate() error { return nil }
func (*TargetHttpsProxy) Validate() error { return nil }
func (*TargetHttpsProxyList) Validate() error { return nil }
func (*TargetHttpsProxyList_Warning) Validate() error { return nil }
func (*TargetInstance) Validate() error { return nil }
func (*TargetInstanceAggregatedList) Validate() error { return nil }
func (*TargetInstanceAggregatedList_Warning) Validate() error { return nil }
func (*TargetInstanceList) Validate() error { return nil }
func (*TargetInstanceList_Warning) Validate() error { return nil }
func (*TargetInstancesScopedList) Validate() error { return nil }
func (*TargetInstancesScopedList_Warning) Validate() error { return nil }
func (*TargetPool) Validate() error { return nil }
func (*TargetPoolAggregatedList) Validate() error { return nil }
func (*TargetPoolAggregatedList_Warning) Validate() error { return nil }
func (*TargetPoolInstanceHealth) Validate() error { return nil }
func (*TargetPoolList) Validate() error { return nil }
func (*TargetPoolList_Warning) Validate() error { return nil }
func (*TargetPoolsAddHealthCheckRequest) Validate() error { return nil }
func (*TargetPoolsAddInstanceRequest) Validate() error { return nil }
func (*TargetPoolsRemoveHealthCheckRequest) Validate() error { return nil }
func (*TargetPoolsRemoveInstanceRequest) Validate() error { return nil }
func (*TargetPoolsScopedList) Validate() error { return nil }
func (*TargetPoolsScopedList_Warning) Validate() error { return nil }
func (*TargetReference) Validate() error { return nil }
func (*TargetSslProxiesSetBackendServiceRequest) Validate() error { return nil }
func (*TargetSslProxiesSetProxyHeaderRequest) Validate() error { return nil }
func (*TargetSslProxiesSetSslCertificatesRequest) Validate() error { return nil }
func (*TargetSslProxy) Validate() error { return nil }
func (*TargetSslProxyList) Validate() error { return nil }
func (*TargetSslProxyList_Warning) Validate() error { return nil }
func (*TargetTcpProxiesSetBackendServiceRequest) Validate() error { return nil }
func (*TargetTcpProxiesSetProxyHeaderRequest) Validate() error { return nil }
func (*TargetTcpProxy) Validate() error { return nil }
func (*TargetTcpProxyList) Validate() error { return nil }
func (*TargetTcpProxyList_Warning) Validate() error { return nil }
func (*TargetVpnGateway) Validate() error { return nil }
func (*TargetVpnGatewayAggregatedList) Validate() error { return nil }
func (*TargetVpnGatewayAggregatedList_Warning) Validate() error { return nil }
func (*TargetVpnGatewayList) Validate() error { return nil }
func (*TargetVpnGatewayList_Warning) Validate() error { return nil }
func (*TargetVpnGatewaysScopedList) Validate() error { return nil }
func (*TargetVpnGatewaysScopedList_Warning) Validate() error { return nil }
func (*TestFailure) Validate() error { return nil }
func (*TestPermissionsRequest) Validate() error { return nil }
func (*TestPermissionsResponse) Validate() error { return nil }
func (*UDPHealthCheck) Validate() error { return nil }
func (*UrlMap) Validate() error { return nil }
func (*UrlMapList) Validate() error { return nil }
func (*UrlMapList_Warning) Validate() error { return nil }
func (*UrlMapReference) Validate() error { return nil }
func (*UrlMapTest) Validate() error { return nil }
func (*UrlMapValidationResult) Validate() error { return nil }
func (*UrlMapsValidateRequest) Validate() error { return nil }
func (*UrlMapsValidateResponse) Validate() error { return nil }
func (*UsageExportLocation) Validate() error { return nil }
func (*VpnTunnel) Validate() error { return nil }
func (*VpnTunnelAggregatedList) Validate() error { return nil }
func (*VpnTunnelAggregatedList_Warning) Validate() error { return nil }
func (*VpnTunnelList) Validate() error { return nil }
func (*VpnTunnelList_Warning) Validate() error { return nil }
func (*VpnTunnelsScopedList) Validate() error { return nil }
func (*VpnTunnelsScopedList_Warning) Validate() error { return nil }
func (*XpnHostList) Validate() error { return nil }
func (*XpnHostList_Warning) Validate() error { return nil }
func (*XpnResourceId) Validate() error { return nil }
func (*Zone) Validate() error { return nil }
func (*ZoneList) Validate() error { return nil }
func (*ZoneList_Warning) Validate() error { return nil }
func (*ZoneSetLabelsRequest) Validate() error { return nil }
